### ISSUE TITLE
Could the virtual DOM be used for ListView Items?

### ISSUE THREAD

**Issue by joewood** [rigdern/react-winjs#1]
I've been looking at react-native, to see how it would be incorporated into WinRT.
In the iOS code, the ListView component (which is an iOS TableView) has a `renderRow` property, which points to a function that returns the a virtual DOM element for the supplied row data.
Could the WinJS ListView class do the same thing? This will mean only materializing the virtual DOM if the data has changed (or if it's being mounted).

**Comment by rigdern** [comment]
Thanks for your feedback, @joewood!

Here's what using a ListView currently looks like:

``` js
var React = require("react");
var ReactWinJS = require("react-winjs")

var App = React.createClass({
    // reactRenderer converts a React component into a DOM element because that's what
    // the ListView expects. It also waits on the itemPromise so you don't have to.
    itemRenderer: ReactWinJS.reactRenderer(function (item) {
        return <div style={{color: "blue"}}>{item.data.title}</div>;
    }),
    getInitialState: function () {
        return {
            bindingList: new WinJS.Binding.List([0, 1, 2, 3])
        };
    },
    render: function () {
        return (
            <ReactWinJS.ListView
                itemDataSource={this.state.bindingList.dataSource}
                itemTemplate={this.itemRenderer} />
        );
    }
})
```

The WinJS ListView already accepts a function as an `itemTemplate`. Because you want to be able to return a React component rather than a DOM element from your `itemTemplate`, you need to do a small amount of conversion. The helper [`reactRenderer`](https://github.com/rigdern/react-winjs/blob/45bd5d19da5c986c7851c4b5fb4483e03c815f82/react-winjs.js#L784-L796) takes care of this for you.

What do you think?

**Comment by joewood** [comment]
Hi Adam

Yes, that's basically what I had.  It all works great, and I've managed to convert over the default Hub/ListView sample for the universal app. And I assume this should just work for the web too, using the npm module (I haven't tried it yet). 

Comparing react-winjs with react-native, there are a couple of areas that need a bit of thinking about:
- The data for the **ListView** in the above is still using a **BindingList**.  In the **react-native** code the iOS ListView uses a conversion class to convert from the immutable properties to the native binding for the TableView in iOS. This provides a cleaner and more consistent solution to data integration that supports immutability. 
- Ideally, it would be great to have the same WinJS React surface API for the web and a native Windows react-native binding (which would be from JavaScript to C++/XAML). I've started playing with this, although it's early days. 

The iOS react-native ListView is created like this, the dataSource object being an instance of `ListViewDataSource`, which is that immutable conversion layer:

``` jsx
 <ListView
        dataSource={this.state.dataSource}
        renderFooter={this.renderFooter}
        renderRow={this.renderRow}
        onEndReached={this.onEndReached}
        showsVerticalScrollIndicator={false}
      />
```

**Comment by joewood** [comment]
BTW - for the helper would `React.addons.createFragment` be a better way to go? Not sure if React is doing any fragment pooling with keys under the hood.

**Comment by rigdern** [comment]
> The data for the ListView in the above is still using a BindingList. In the react-native code the iOS ListView uses a conversion class to convert from the immutable properties to the native binding for the TableView in iOS. This provides a cleaner and more consistent solution to data integration that supports immutability.

I haven't played with react-native. What kind of collection data structure do apps use when not using a ListView? Does `ListViewDataSource` enable them to use that same data structure with a ListView?

In React web apps, developers use arrays everywhere so I imagine they'd want to be able to just use an array with their react-winjs ListView. I'm still thinking about how I'd like to implement that.

> Ideally, it would be great to have the same WinJS React surface API for the web and a native Windows react-native binding (which would be from JavaScript to C++/XAML). I've started playing with this, although it's early days.

That's an interesting idea. However, in general XAML and WinJS controls have different API surfaces. The approach I've been following with react-winjs is just exposing the API surface of the WinJS controls as directly as possible. The benefits are that the documentation for WinJS is relevant for react-winjs and that if you already use WinJS, it's easy to pick up react-winjs.

Also, you mentioned a "Windows react-native binding" and that you've "started playing with this". Are you making a Windows react-native binding?

> BTW - for the helper would React.addons.createFragment be a better way to go? Not sure if React is doing any fragment pooling with keys under the hood.

I wasn't familiar with `createFragment`. I just read about it but I'm not sure I follow you. I assume you are suggesting using it in the implementation of [`reactRenderer`](https://github.com/rigdern/react-winjs/blob/45bd5d19da5c986c7851c4b5fb4483e03c815f82/react-winjs.js#L784-L796) instead of `React.render`. Can you elaborate on why you'd think it'd be useful here?

**Comment by joewood** [comment]
On **react-native** - it's a react pattern abstraction over native GUI components. This means exposing the native GUI classes on each platform as direct React style components (it's not a GUI framework abstraction). The development version on GitHub is for iOS, but there's also an Android version in development. The iOS version uses JSCore for the application code. No DOM components are used, instead changes in the visual tree are sent over a thread boundary to native (Objective C) code where the native GUI component tree is modified. The native XAML WinRT components would be a good candidate for the abstraction because of the already exposed meta-data and consistent primitive type system. I've just started playing with the react-native code to see how feasible it is (and better understand the Facebook code).  I can imagine this is going to be very popular (maybe game changing, especially from existing Cordova/ReactJS users). The performance is very good as can be seen from the [intro video](https://www.youtube.com/watch?v=KVZ-P-ZI6W4&t=173).

On the iOS ListViewDataSource class from react-native, this actually looks like it's bypassing any of the binding and lifetime management on the native side. It uses a regular array of opaque objects. From reading the source (which is still changing quite a bit), this looks like it's handling sections of immutable data to optimize native GUI element creation. So for the WinJS ListView it would need to add child rows directly and manage the scroll position/range of the container. So, basically handing control of row lifetime management to React rather than the origin ListView behavior.

For `createFragment` - for the **ListView** where the lifetime management is delegated to the control I guess this doesn't matter. It would be interesting if ListView could be used without binding. My concern was really around doc fragment reuse based on immutable data - which wouldn't apply.

**Comment by RReverser** [comment]
> I've been looking at react-native, to see how it would be incorporated into WinRT.

Same here. Actually found this project when tried to finally publish initial version of own `react-winjs` to npm and found out that it's already taken :)

**Comment by RReverser** [comment]
However, I already managed to patch webpack and create some basic setup that allows to hot-reload components right on the Windows Phone so that you have web-ish development experience for native apps. I'll try to publish that setup + example soon and not to get too late with that part too.

**Comment by joewood** [comment]
Hi @RReverser, does your hot reload use WinJS with webpack and reactjs?
I was thinking of using this same reacjs interface with the react-native bridge into a XAML/C++ native layer.  This would avoid a GC on the UI thread, but still keep the WinJS react interface.

**Comment by RReverser** [comment]
> Hi @RReverser, does your hot reload use WinJS with webpack and reactjs?

Yes.

> I was thinking of using this same reacjs interface with the react-native bridge into a XAML/C++ native layer.

You mean, building similar bindings as in iOS version, to native XAML components? Doubt that it will be worth efforts, but you could try.

**Comment by joewood** [comment]
It should be, given the advantages of react-native over regular react.js. An interesting experiment at least.

**Comment by RReverser** [comment]
I rather feel that having native stuff exposed to JS in Windows ecosystem (without WebView layer) is a serious advantage that makes native bindings unnecessary and probably even more expensive.

**Comment by joewood** [comment]
Sorry, don't quite follow. I think WinJS, although very fast, is still the HTML DOM. React-Native has the advantage of a react based JS 'hot-loaded' environment, but the speed of real native UI components running on a thread without GC interruption.

**Comment by RReverser** [comment]
How are you going to do that without GC? Like, when to release memory for components that are gone and so?

**Comment by joewood** [comment]
the WinRT C++ environment is essentially COM, so no GC is involved.

**Comment by RReverser** [comment]
It is, but in C++ you have to manage memory on your own. How are you going to do that when only JS(X) knows which components are needed at the moment and which are not needed no more?

**Comment by joewood** [comment]
The C++ code will handle the virtual DOM delta, then make modifications accordingly. Again, this is experimental - but it follows the same pattern in the existing iOS code in Reat-Native.  It's all reference counted, so the memory is handled but in the more deterministic way.

**Comment by rigdern** [comment]
Now being tracked by winjs/react-winjs#1.
